### ISSUE TITLE
Other datasets

### ISSUE THREAD

**Issue by debasmitdas** [anshuln/Training-for-the-Future#1]
I acknowledge your wonderful work. Could you also share the processed datasets - Shuttle and Reuters like you did for the other datasets in Google drive ?

**Comment by anshuln** [comment]
Thanks for the interest in our work. 
You can find the shuttle dataset [here](https://drive.google.com/file/d/13C6xyw0idv62d7CGzSgmkhcb-N7CNyfS/view). We shall update the reuters dataset soon.
